### PR TITLE
Updated Doodle

### PR DESCRIPTION
**Pull request by rajivaPavan**

### CODE REVIEW

**Review by sandilsranasinghe — COMMENTED** [review]
Is there a particular reason we've moved it to the very left

**Comment by rajivaPavan** [comment]
It looks better, I think

**Comment by sandilsranasinghe** [comment]
> @sandilsranasinghe It looks better, I think

Can we move it a little to the right (on laptop size)? It's almost touching the left side of the screen.

**Comment by rajivaPavan** [comment]
Wdym? In the laptop size, the doodle is in the right center, isn't it?

**Comment by sandilsranasinghe** [comment]
Screenshot from 2022-09-21 16-24-32

**Comment by sandilsranasinghe** [comment]
nevermind, this is a problem with firefox only. We'll merge this in and try to fix that later as a bug

**Review by sandilsranasinghe — APPROVED** [review]

**Pull request merged**
